/// MANIFEST LINKS:
/// Principles: P-010 (Sport Identity - Bot)
-- ============================================================================
-- BOT PATHFINDING
-- ============================================================================
-- Uses GMod's native NavMesh (generated by nav_generate / sv_nav.lua).
-- Falls back to direct line-of-sight movement when no nav mesh is loaded.
--
-- nav_generate is triggered automatically on first map load via sv_nav.lua.
-- The generated .nav file is saved to maps/<mapname>.nav and reused forever.
-- ============================================================================

BotPathfinder      = {}
BotPathfinder.Cache           = {} -- nextWaypoint Vector per bot
BotPathfinder.LastUpdate      = {} -- CurTime() of last A* calculation per bot
BotPathfinder.HazardAreas     = {} -- nav area IDs overlapping a kill/reset trigger
BotPathfinder.HazardCacheBuilt = false

local pathUpdateInterval = 0.5 -- Seconds between A* recalculations

-- ============================================================================
-- Path reconstruction helper (A*)
-- ============================================================================

local function ReconstructPath(cameFrom, current, startArea)
	local path = {}
	local curr = current
	while curr do
		table.insert(path, 1, curr)
		if curr == startArea then break end
		curr = cameFrom[curr:GetID()]
	end
	return path
end

-- ============================================================================
-- Hazard area cache
-- ============================================================================
-- Built once after the nav mesh loads. Any nav area whose bounding volume
-- overlaps a trigger_hurt, trigger_ballreset, or trigger_kill is marked here.
-- A* skips these areas so bots never plan routes through death zones.

local HAZARD_CLASSES = { trigger_hurt = true, trigger_ballreset = true, trigger_kill = true }

local function BuildHazardCache()
	BotPathfinder.HazardAreas = {}
	for _, area in pairs(navmesh.GetAllNavAreas()) do
		local c0, c1, c2, c3 = area:GetCorner(0), area:GetCorner(1), area:GetCorner(2), area:GetCorner(3)
		local minZ = math.min(c0.z, c1.z, c2.z, c3.z)
		local maxZ = math.max(c0.z, c1.z, c2.z, c3.z)
		local mins = Vector(
			math.min(c0.x, c1.x, c2.x, c3.x),
			math.min(c0.y, c1.y, c2.y, c3.y),
			minZ - 128
		)
		local maxs = Vector(
			math.max(c0.x, c1.x, c2.x, c3.x),
			math.max(c0.y, c1.y, c2.y, c3.y),
			maxZ + 64
		)
		for _, ent in pairs(ents.FindInBox(mins, maxs)) do
			if HAZARD_CLASSES[ent:GetClass()] then
				BotPathfinder.HazardAreas[area:GetID()] = true
				break
			end
		end
	end
	BotPathfinder.HazardCacheBuilt = true
end

-- ============================================================================
-- Public API
-- ============================================================================

--- Find the next waypoint toward targetPos.
--- Fallback chain: EFTNav graph → GMod NavMesh A* → nil (direct LOS)
---@param bot      Player  The bot entity
---@param targetPos Vector  Destination position
---@return Vector|nil
function BotPathfinder.GetNextWaypoint(bot, targetPos)
	local botPos = bot:GetPos()

	-- ── 1. EFTNav hand-placed node graph (primary) ────────────────────────
	-- Skipped when no graph is loaded for this map; falls through to NavMesh.
	if EFTNav.IsLoaded() then
		-- Direct LOS check first — if nothing blocks us, no pathfinding needed.
		local tr = util.TraceHull({
			start  = botPos    + Vector(0, 0, 10),
			endpos = targetPos + Vector(0, 0, 10),
			mins   = Vector(-16, -16, 0),
			maxs   = Vector( 16,  16, 72),
			mask   = MASK_SOLID,
			filter = function(ent)
				if ent:IsPlayer() or ent:IsNPC() then return false end
				return true
			end
		})

		if not tr.Hit then
			-- Clear path — go direct, clear any jump flags.
			bot.PathJumpLink = false
			return nil
		end

		-- Throttle A* recalculation.
		if BotPathfinder.LastUpdate[bot] and
		   CurTime() - BotPathfinder.LastUpdate[bot] < pathUpdateInterval then
			return BotPathfinder.Cache[bot]
		end

		local path = EFTNav.FindPath(botPos, targetPos)
		if path and path[2] then
			local nextNode  = path[2]
			local waypoint  = nextNode.pos
			-- Small jitter so bots don't all walk the exact same line.
			waypoint = waypoint + Vector(math.random(-15, 15), math.random(-15, 15), 0)

			-- Jump flag: explicit link tag overrides height-based detection.
			local link = path[1].links[nextNode.id]
			bot.PathJumpLink = link and link.jump or false
			bot.PathJump     = (not bot.PathJumpLink) and (waypoint.z > botPos.z + 64)

			BotPathfinder.Cache[bot]      = waypoint
			BotPathfinder.LastUpdate[bot] = CurTime()
			return waypoint
		end

		-- EFTNav found no path (disconnected graph?) — fall through to NavMesh.
	end

	-- ── 2. GMod NavMesh A* (fallback) ────────────────────────────────────
	if not navmesh.IsLoaded() then return nil end
	if not BotPathfinder.HazardCacheBuilt then BuildHazardCache() end

	-- Direct LOS check: hull trace matching player physics.
	-- If nothing is in the way, skip A* entirely and move straight.
	local tr = util.TraceHull({
		start  = botPos    + Vector(0, 0, 10),
		endpos = targetPos + Vector(0, 0, 10),
		mins   = Vector(-16, -16,  0),
		maxs   = Vector( 16,  16, 72),
		mask   = MASK_SOLID,
		filter = function(ent)
			-- Only care about map geometry, not other players/bots
			if ent:IsPlayer() or ent:IsNPC() then return false end
			return true
		end
	})
	if not tr.Hit then return nil end -- Clear path, direct move

	-- Throttle: return cached waypoint if we calculated recently
	if BotPathfinder.LastUpdate[bot] and
	   CurTime() - BotPathfinder.LastUpdate[bot] < pathUpdateInterval then
		return BotPathfinder.Cache[bot]
	end

	-- A* over GMod NavMesh areas
	local startArea = navmesh.GetNavArea(botPos,    200)
	local endArea   = navmesh.GetNavArea(targetPos, 200)

	if not IsValid(startArea) or not IsValid(endArea) then return nil end
	if startArea == endArea then return nil end -- Same area, go direct

	local openSet  = {startArea}
	local cameFrom = {}
	local gScore   = {[startArea:GetID()] = 0}
	local fScore   = {[startArea:GetID()] = startArea:GetCenter():Distance(targetPos)}

	local loops    = 0
	local maxLoops = 200 -- Safety cap

	while #openSet > 0 and loops < maxLoops do
		loops = loops + 1

		-- Pick area with lowest fScore
		local current, currentIndex
		local lowestF = math.huge
		for i, area in ipairs(openSet) do
			local f = fScore[area:GetID()] or math.huge
			if f < lowestF then
				lowestF      = f
				current      = area
				currentIndex = i
			end
		end

		if current == endArea then
			local path = ReconstructPath(cameFrom, current, startArea)
			if path[2] then
				local waypoint  = path[2]:GetCenter()
				-- Small jitter to prevent bot trains on shared paths
				waypoint.x = waypoint.x + math.random(-20, 20)
				waypoint.y = waypoint.y + math.random(-20, 20)

				-- Jump hint: if next area is meaningfully higher, tell the bot.
				-- 64 HU = one player step-up; avoids false triggers on slight terrain.
				bot.PathJump = waypoint.z > botPos.z + 64

				BotPathfinder.Cache[bot]      = waypoint
				BotPathfinder.LastUpdate[bot] = CurTime()
				return waypoint
			end
			return nil
		end

		table.remove(openSet, currentIndex)

		for _, neighbor in ipairs(current:GetAdjacentAreas()) do
			local nID = neighbor:GetID()
			if BotPathfinder.HazardAreas[nID] then continue end -- skip death zones
			local tentativeG = gScore[current:GetID()] +
			                   current:GetCenter():Distance(neighbor:GetCenter())

			if tentativeG < (gScore[nID] or math.huge) then
				cameFrom[nID] = current
				gScore[nID]   = tentativeG
				fScore[nID]   = gScore[nID] + neighbor:GetCenter():Distance(targetPos)

				local inOpen = false
				for _, a in ipairs(openSet) do
					if a == neighbor then inOpen = true; break end
				end
				if not inOpen then
					table.insert(openSet, neighbor)
				end
			end
		end
	end

	return nil -- No path found within budget
end
