from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

GENERATOR = "tools/indexer"
SCHEMA_VERSION = 1

MARKDOWN_BANNER = (
    "> Generated by Tools/Indexer. Do not hand-edit unless deliberately "
    "converting this into source documentation.\n"
)


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def rel(path: Path, root: Path) -> str:
    try:
        return str(path.resolve().relative_to(root.resolve())).replace("\\", "/")
    except ValueError:
        return str(path).replace("\\", "/")


@dataclass
class IndexEnvelope:
    repo_root: Path
    warnings: list[str] = field(default_factory=list)

    def warn(self, msg: str) -> None:
        self.warnings.append(msg)

    def envelope(self) -> dict[str, Any]:
        return {
            "generated_by": GENERATOR,
            "schema_version": SCHEMA_VERSION,
            "generated_at": utc_now(),
            "repo_root": ".",
            "warnings": list(self.warnings),
        }

    def wrap(self, payload: dict[str, Any]) -> dict[str, Any]:
        out = self.envelope()
        out.update(payload)
        out["warnings"] = list(self.warnings)
        return out


def dumps(data: dict[str, Any]) -> str:
    return json.dumps(data, indent=2, sort_keys=False) + "\n"
