"""Output helpers for EFT2 simulation readiness reports."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def render_markdown(report: dict[str, Any]) -> str:
    summary = report["summary"]
    lines = [
        "# EFT2 Simulation Readiness",
        "",
        f"Generated by `{report['generated_by']}`.",
        "",
        "This is a readiness report, not simulation output. It does not claim any scenario is executable without a real gameplay runtime and telemetry emitter.",
        "",
        "## Summary",
        "",
        f"- scenarios defined: {summary['scenarios_defined']}",
        f"- telemetry events defined: {summary['telemetry_events_defined']}",
        f"- candidate maps: {summary['candidate_maps']}",
        f"- map-analysis-ready maps: {summary['map_analysis_ready']}",
        f"- reported maps in this run: {summary['reported_maps']}",
        f"- reported map-analysis-ready maps: {summary['reported_map_analysis_ready']}",
        f"- runtime present: {summary['gameplay_runtime_present']}",
        f"- telemetry emitter present: {summary['telemetry_emitter_present']}",
        f"- core loop simulatable: {summary.get('core_loop_simulatable', False)}",
        "",
        "## Blockers",
        "",
    ]
    for blocker in report["blockers"]:
        lines.append(f"- `{blocker['id']}`: {blocker['message']}")
    if not report["blockers"]:
        lines.append("- none")

    core = report.get("core_loop_simulation") or {}
    lines.extend(["", "## Core Loop Simulation", ""])
    lines.append(f"- can simulate core loop: {core.get('can_simulate_core_loop', False)}")
    lines.append(f"- scope: {core.get('scope', 'not assessed')}")
    supported = core.get("supported_scenarios") or []
    lines.append(f"- supported scenario slices: {', '.join(f'`{item}`' for item in supported) if supported else 'none'}")
    missing_events = core.get("missing_telemetry_events") or []
    lines.append(f"- missing core telemetry events: {', '.join(f'`{item}`' for item in missing_events) if missing_events else 'none'}")
    lines.append(f"- map/rule refinement note: {core.get('map_rule_refinement_note', 'not assessed')}")

    lines.extend(["", "## Scenario Readiness", ""])
    for row in report["scenario_readiness"]:
        labels = ", ".join(f"`{label}`" for label in row["labels"])
        lines.append(f"- `{row['id']}` {row['title']}: {labels}")

    lines.extend(["", "## Map Readiness", ""])
    for row in report["map_readiness"]:
        labels = ", ".join(f"`{label}`" for label in row["labels"])
        lines.append(f"- `{row['map']}`: {labels}")

    lines.extend(["", "## Recommended First Targets", ""])
    for target in report["recommended_first_targets"]:
        lines.append(f"- `{target['scenario_id']}` on `{target['map']}`: {target['status']} - {target['reason']}")

    lines.extend([
        "",
        "## Evidence Limits",
        "",
        "- Real `lua/game logs` and map analyzer outputs are calibration evidence, not an executable simulation runtime.",
        "- Existing abstract map outputs can guide future modeling but should not be reported as live gameplay results.",
        "- Scenario/map pairs become executable only after gameplay code and host-side telemetry emitters exist.",
    ])
    return "\n".join(lines) + "\n"


def write_markdown(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_markdown(data), encoding="utf-8")
